### ISSUE TITLE
Mapillary API v 4

### ISSUE THREAD

**Issue by MutantKiwi** [wladich/nakarte#687]
Mapillary is updating its API in May 2020 and will be built primarily around vector tiles, rather than GeoJSON. v3 will depreciate soon afterwards. Is it possible to support?

https://blog.mapillary.com/update/2021/03/03/preparing-for-the-new-mapillary-api.html

**Comment by wladich** [comment]
I can not find any other information besides that blog post - no follow ups in the blog, no new API specs, nothing.

As I am using official JS API I hope there will be not too many changes required.

**Comment by wladich** [comment]
So it happened, API V4 is here and V3 is planned to be decommissioned on August 18.

There is no good "transition" documentation and there are mistakes in examples ... sigh.

But that is not the worst part: mapillary vector tiles were always quite huge, but in the new version they became even bigger and terribly slow to parse. In a small test for densely populated area the time for loading all tiles on the screen has increased from ~16 seconds to ~2 minutes which is unacceptable.  Also amount of data downloaded to initially display the coverage is about 40 Mb! 
The application at mapillary.com works faster due to utilization of all 8 CPUs on my i7. I do not know if optimizations like WASM are also used, but anyway with ServiceWorkers with a fast CPU the coverage will load too long and download too much data.

Tomorrow I am leaving for vacation for one month so it is expected that at August 18 mapillary will stop working in nakarte.me.

I plan to write a server-side proxy for mapillary requests. It will
- serve tile requests
- serve search requests

On a request for a tile it will download vector tile from mapillary, parse it an render coverage image. Tiles will be cached, presumably by the nginx. 
On a request for nearest images it will download vector tile at level 14, parse it and store for future use, presumably in some sort of spatial index. The same should also be done when processing tile at level 14 for the purpose of rendering coverage image.

**Comment by MutantKiwi** [comment]
Thanks for looking into this. I will follow up with one of Mapillary Project Managers and get some feedback for you. Enjoy your break!

**Comment by wladich** [comment]
I see following issues with using vector tiles in browser for displaying images coverage and performing spatial search:
- Tiles are huge. This [view](https://www.mapillary.com/app/?lat=55.548024160292385&lng=37.58398117141178&z=9.098514053650906) generates 45 Mb of traffic from tiles.mapillary.com.  Some people might be unhappy downloading that much over cellular network.
- Tiles are slow to decode. Official mapillary web app renders this view in about 6 seconds when tiles are cached in browser utilizing 8 threads of i7 CPU. Many users have much slower machines. 
-  Tiles a slow to download. I often observe download times of about 10 seconds for tiles several megabytes large. In successive attempts download time becomes smaller, I guess because of caching on CDN.
- Doing spatial search in-browser requires to download tiles at level 14. And those tiles are sometimes several megabytes large. So  when a user clicks map and browser needs to get a single number (image ID), we need to download several megabytes! 

So I started investigating possibilities of building a server which could provide raster coverage tiles and do spatial search. 
I tried to download some data from tiles.mapillary.com to preload cache for the server but after some period of time I start to receive "302" responses, which I guess should be interpreted as a ban for exceeding request rate limit. I could not find information about allowed request rate in Mapillary API documentation or Terms of use. I also could not figure it out by experimenting as sometimes I am being banned after making requests at a rate of 1 request per second for about 2 minutes.

@MutantKiwi could you please tell me, at what rate my server can do requests to tiles.mapillary.com without being banned?

**Comment by MutantKiwi** [comment]
@wladich Thanks for follow-up . Have reached out to my contact for comment.

**Comment by wladich** [comment]
Fixed by #982

**Comment by wladich** [comment]
Rendering server: https://github.com/wladich/mapillaryRender
